version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: sales
        description: "Sales data"
        loaded_at_field: _dlt_load_id
        freshness: {warn_after: {count: 6, period: hour}, error_after: {count: 12, period: hour}}
        columns:
          - name: order_id
            tests:
              - not_null
      - name: fx_rates
        description: "Foreign exchange rates"
        loaded_at_field: _dlt_load_id
        freshness: {warn_after: {count: 24, period: hour}, error_after: {count: 36, period: hour}}
        columns:
          - name: rate_date
            tests:
              - not_null
          - name: currency
            tests:
              - not_null
          - name: rate
            tests:
              - not_null
      - name: countries
        columns:
          - name: names__common
            tests:
              - not_null
              - unique
      - name: countries__currencies
      - name: _dlt_loads